name: Deploy React Vite to GitHub Pages

on:
  push:
    branches:
      - projectReactViteRemake  # Tự động chạy khi push vào nhánh này

permissions:
  contents: write  # Cho phép ghi vào repo (để đẩy lên gh-pages)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
